version: "2"

run:
  timeout: 5m
  exclude-dirs:
    - api/gen
    - vendor

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused

  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true